### ISSUE TITLE
Setup instructions using Sqlite3 as the database don’t (appear to) work

### ISSUE THREAD

**Issue by andylolz** [IATI/preview-website#197]
The setup instructions suggest it should be fine to use Sqlite3. However, upon calling `python manage.py migrate_translation`, I hit a couple of errors.

Firstly:

```
Applying search.0001_initial...Traceback (most recent call last):
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/base/operations.py", line 281, in prepare_sql_script
    import sqlparse
ModuleNotFoundError: No module named 'sqlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/wagtail_modeltranslation/management/commands/migrate_translation.py", line 25, in handle
    super(Command, self).handle(*args, **options)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 105, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 128, in _run_sql
    statements = schema_editor.connection.ops.prepare_sql_script(sqls)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/base/operations.py", line 284, in prepare_sql_script
    "sqlparse is required if you don't split your SQL "
django.core.exceptions.ImproperlyConfigured: sqlparse is required if you don't split your SQL statements manually.
```

Secondly:

```
Applying search.0001_initial...Traceback (most recent call last):
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 301, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "CASCADE": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/wagtail_modeltranslation/management/commands/migrate_translation.py", line 25, in handle
    super(Command, self).handle(*args, **options)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 105, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 126, in _run_sql
    schema_editor.execute(sql, params=params)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 301, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "CASCADE": syntax error
```

**Comment by allthatilk** [comment]
@andylolz The most current README is in the `add-page-models` branch but has not currently been updated as a priority. The current website was never setup with the intention to be compatible with SQLite3 as other processes are dependent on postgresql. As there is little purpose for us to add features to this site that deviate from production setup, it is unlikely that we will be revisiting this any time soon.

**Comment by allthatilk** [comment]
I have now made changes to the README which are in the process of being merged down. Once these are on master I will be closing this PR. I have marked #198 as out of scope for the reasons previously mentioned and closed it.

**Comment by allthatilk** [comment]
README changes now on master with #222 merged down. Closing this issue.
