### ISSUE TITLE
Reference redirects raise server errors

### ISSUE THREAD

**Issue by andylolz** [IATI/preview-website#215]
E.g.:
http://iatistandard.org/203/codelists

…looks like this:
![screen shot 2018-07-20 at 12 59 37](https://user-images.githubusercontent.com/464193/43001336-cd1698a0-8c1c-11e8-8050-18ca0700efec.png)

The error raised looks like this:

```
Internal Server Error: /203/codelists
Traceback (most recent call last):
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/IATI-website/pyenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: reference_redirect() takes 1 positional argument but 2 were given
[20/Jul/2018 12:01:01] "GET /203/codelists HTTP/1.1" 500 66218
```

It’s complaining about 2 arguments because of the capture group in the regex:

```python
r'^(101|102|103|104|105|201|202|203|activity-standard|codelists|developer|introduction|namespaces-extensions|organisation-identifiers|organisation-standard|reference|rulesets|schema|upgrades)/'
```

I.e. the brackets are defining a capture group, but we don’t care about what they’re capturing, so we can just ignore it using `?:`.

---

~~I’m a bit confused why this previously worked but now doesn’t – the code looks like it was never correct. I wonder if this redirecting was previously handled by apache/nginx, so this code was never hit. Is that possible? If so, does that indicate that something at webserver level has now broken, meaning this code does now get used?~~ See comment below.

**Comment by andylolz** [comment]
Fixed in #214.
